server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/portshop
    username: mymy
    password: 123456
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 749258993358-ngli1u6bcns01d0cs3cr9fsidohoqj5v.apps.googleusercontent.com
#            client-secret: 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

